### ISSUE TITLE
POST /annotation route and test

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN-services#5]
This is ends up under the general /createSomething suite of endpoints that will look to create something in RERUM.

Annotation Pages will contain individual Annotations which target the portions of the Canvases they apply to.

**Comment by cubap** [comment]
I propose, to support our use cases without excessive troubles down the line, not creating routes for all these.

Argument against is that we can apply validation schemas to the individual submissions. In fact, we can apply the boilerplate of the app and not send it along every time.

*however*

If this logic is sent to a handler instead, we never have to worry about route collisions, accidentally missed "s" for a batch create, etc. In fact, if the route is `/save` we can upsert and decide what is needed for each. 

Properly done LOUD will tell us what the `type` is, so we can pass it to the correct validator anyway. This will hopefully simplify testing as well, since we can feed the `saveController` the new type of object and just expect the correct handling.

**Comment by thehabes** [comment]
This will be handled elsewhere and we will not need a specific route like `/annotation`.  It will be a part of the Annotation Collection and Annotation Page workflow, as creating a new Annotation will mean placing one into a new or existing Annotation Page.
